In [1]:
# pip install --upgrade MetaTrader5

In [2]:
import numpy
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime

In [3]:
if not mt5.initialize(login=89500879, server="MetaQuotes-Demo", password="6kF-FhYd"):
    print("Initialization failed")
    print(mt5.last_error())
    quit()

print("Connected to MT5 successfully")

Connected to MT5 successfully

In [9]:
#INPUTS
# SYMBOLS = AUDSD, EURUSD,EURJPY, XAUUSD, EURGPY, USDJPY
symbol = "AUDUSD"
timeframe = mt5.TIMEFRAME_M1  # 1-minute timeframe
utc_from = datetime(2025, 1, 17)
utc_to = datetime(2025, 1, 20)

In [10]:
startdate=utc_from.strftime('%Y%m%d')
enddate=utc_to.strftime('%Y%m%d')

In [11]:
# Get the OHLC data
rates = mt5.copy_rates_range(symbol, timeframe, utc_from, utc_to)

# Check if the data is downloaded successfully
if rates is None:
    print("No data available, error code =", mt5.last_error())
else:
    # Convert the data to a pandas DataFrame
    rates_frame = pd.DataFrame(rates)
    # Convert the time in seconds to a datetime format
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')

    # Display the data
    print(rates_frame)

                    time     open     high      low    close  tick_volume  \
0    2025-01-16 16:00:00  0.62065  0.62069  0.62047  0.62050           53
1    2025-01-16 16:01:00  0.62051  0.62054  0.62044  0.62044           44
2    2025-01-16 16:02:00  0.62043  0.62050  0.62031  0.62039           42
3    2025-01-16 16:03:00  0.62041  0.62044  0.62031  0.62036           45
4    2025-01-16 16:04:00  0.62036  0.62038  0.62026  0.62026           45
...                  ...      ...      ...      ...      ...          ...
1360 2025-01-17 14:40:00  0.61858  0.61860  0.61846  0.61853           50
1361 2025-01-17 14:41:00  0.61853  0.61857  0.61849  0.61851           25
1362 2025-01-17 14:42:00  0.61850  0.61855  0.61848  0.61854           29
1363 2025-01-17 14:43:00  0.61854  0.61854  0.61841  0.61849           30
1364 2025-01-17 14:44:00  0.61847  0.61847  0.61839  0.61842           19

      spread  real_volume
0          8            0
1          8            0
2          8            0
3          8            0
4          8            0
...      ...          ...
1360       8            0
1361       8            0
1362       8            0
1363       8            0
1364       8            0

[1365 rows x 8 columns]

In [12]:
rates_frame.drop(["tick_volume", "spread", "real_volume"], inplace=True, axis=1)

In [13]:
rates_frame.tail(40)

                    time     open     high      low    close
1325 2025-01-17 14:05:00  0.61961  0.61970  0.61959  0.61968
1326 2025-01-17 14:06:00  0.61969  0.61979  0.61969  0.61975
1327 2025-01-17 14:07:00  0.61975  0.61989  0.61974  0.61988
1328 2025-01-17 14:08:00  0.61988  0.61992  0.61983  0.61983
1329 2025-01-17 14:09:00  0.61983  0.61986  0.61978  0.61985
1330 2025-01-17 14:10:00  0.61985  0.61992  0.61985  0.61991
1331 2025-01-17 14:11:00  0.61992  0.61993  0.61980  0.61981
1332 2025-01-17 14:12:00  0.61981  0.61988  0.61979  0.61984
1333 2025-01-17 14:13:00  0.61985  0.61992  0.61983  0.61990
1334 2025-01-17 14:14:00  0.61991  0.61991  0.61976  0.61986
1335 2025-01-17 14:15:00  0.61986  0.61986  0.61971  0.61974
1336 2025-01-17 14:16:00  0.61974  0.61974  0.61967  0.61971
1337 2025-01-17 14:17:00  0.61970  0.61974  0.61970  0.61972
1338 2025-01-17 14:18:00  0.61972  0.61976  0.61970  0.61970
1339 2025-01-17 14:19:00  0.61971  0.61975  0.61961  0.61963
1340 2025-01-17 14:20:00  0.61963  0.61963  0.61958  0.61963
1341 2025-01-17 14:21:00  0.61963  0.61966  0.61956  0.61959
1342 2025-01-17 14:22:00  0.61961  0.61970  0.61960  0.61966
1343 2025-01-17 14:23:00  0.61965  0.61965  0.61957  0.61960
1344 2025-01-17 14:24:00  0.61960  0.61962  0.61958  0.61960
1345 2025-01-17 14:25:00  0.61960  0.61973  0.61957  0.61969
1346 2025-01-17 14:26:00  0.61968  0.61968  0.61959  0.61959
1347 2025-01-17 14:27:00  0.61958  0.61960  0.61948  0.61949
1348 2025-01-17 14:28:00  0.61948  0.61949  0.61939  0.61940
1349 2025-01-17 14:29:00  0.61942  0.61948  0.61935  0.61936
1350 2025-01-17 14:30:00  0.61933  0.61936  0.61908  0.61909
1351 2025-01-17 14:31:00  0.61909  0.61913  0.61897  0.61913
1352 2025-01-17 14:32:00  0.61914  0.61918  0.61909  0.61911
1353 2025-01-17 14:33:00  0.61909  0.61909  0.61899  0.61906
1354 2025-01-17 14:34:00  0.61904  0.61907  0.61897  0.61900
1355 2025-01-17 14:35:00  0.61899  0.61909  0.61890  0.61905
1356 2025-01-17 14:36:00  0.61906  0.61908  0.61899  0.61905
1357 2025-01-17 14:37:00  0.61905  0.61912  0.61900  0.61901
1358 2025-01-17 14:38:00  0.61901  0.61901  0.61890  0.61890
1359 2025-01-17 14:39:00  0.61890  0.61894  0.61883  0.61883
1360 2025-01-17 14:40:00  0.61858  0.61860  0.61846  0.61853
1361 2025-01-17 14:41:00  0.61853  0.61857  0.61849  0.61851
1362 2025-01-17 14:42:00  0.61850  0.61855  0.61848  0.61854
1363 2025-01-17 14:43:00  0.61854  0.61854  0.61841  0.61849
1364 2025-01-17 14:44:00  0.61847  0.61847  0.61839  0.61842

In [14]:
rates_frame.to_csv(f'./OHLC_data/{symbol}_{startdate}_{enddate}.csv', index=False)