In [1]:
# pip install --upgrade MetaTrader5

In [2]:
import numpy
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime

In [3]:
# Initialize the connection
if not mt5.initialize():
    print("initialize() failed, error code =", mt5.last_error())
    quit()

In [14]:
#INPUTS
# SYMBOLS = AUDSD, EURUSD,EURJPY, XAUUSD, EURGPY, USDJPY
symbol = "AUDUSD"
timeframe = mt5.TIMEFRAME_M1  # 1-minute timeframe
utc_from = datetime(2025, 1, 16)
utc_to = datetime(2025, 1, 18)

In [15]:
startdate=utc_from.strftime('%Y%m%d')
enddate=utc_to.strftime('%Y%m%d')

In [16]:
# Get the OHLC data
rates = mt5.copy_rates_range(symbol, timeframe, utc_from, utc_to)

# Check if the data is downloaded successfully
if rates is None:
    print("No data available, error code =", mt5.last_error())
else:
    # Convert the data to a pandas DataFrame
    rates_frame = pd.DataFrame(rates)
    # Convert the time in seconds to a datetime format
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')

    # Display the data
    print(rates_frame)

                    time     open     high      low    close  tick_volume  \
0    2025-01-15 16:00:00  0.62431  0.62436  0.62414  0.62435           77
1    2025-01-15 16:01:00  0.62435  0.62435  0.62410  0.62413           59
2    2025-01-15 16:02:00  0.62413  0.62435  0.62410  0.62434           66
3    2025-01-15 16:03:00  0.62432  0.62433  0.62413  0.62431           54
4    2025-01-15 16:04:00  0.62429  0.62433  0.62403  0.62403           69
...                  ...      ...      ...      ...      ...          ...
1486 2025-01-16 16:46:00  0.62032  0.62032  0.62008  0.62026           61
1487 2025-01-16 16:47:00  0.62024  0.62041  0.62024  0.62033           55
1488 2025-01-16 16:48:00  0.62033  0.62050  0.62030  0.62038           53
1489 2025-01-16 16:49:00  0.62038  0.62040  0.62031  0.62033           53
1490 2025-01-16 16:50:00  0.62032  0.62033  0.62025  0.62033           12

      spread  real_volume
0          8            0
1          8            0
2          8            0
3          8            0
4          8            0
...      ...          ...
1486      11            0
1487      11            0
1488      11            0
1489      11            0
1490      11            0

[1491 rows x 8 columns]

In [17]:
rates_frame.drop(["tick_volume", "spread", "real_volume"], inplace=True, axis=1)

In [18]:
rates_frame.tail(40)

                    time     open     high      low    close
1451 2025-01-16 16:11:00  0.62031  0.62040  0.62029  0.62038
1452 2025-01-16 16:12:00  0.62035  0.62037  0.62017  0.62018
1453 2025-01-16 16:13:00  0.62020  0.62029  0.62020  0.62024
1454 2025-01-16 16:14:00  0.62022  0.62037  0.62022  0.62028
1455 2025-01-16 16:15:00  0.62032  0.62038  0.62026  0.62028
1456 2025-01-16 16:16:00  0.62028  0.62048  0.62028  0.62045
1457 2025-01-16 16:17:00  0.62046  0.62063  0.62044  0.62058
1458 2025-01-16 16:18:00  0.62057  0.62069  0.62052  0.62068
1459 2025-01-16 16:19:00  0.62067  0.62070  0.62059  0.62070
1460 2025-01-16 16:20:00  0.62070  0.62073  0.62059  0.62063
1461 2025-01-16 16:21:00  0.62061  0.62066  0.62061  0.62062
1462 2025-01-16 16:22:00  0.62062  0.62071  0.62060  0.62063
1463 2025-01-16 16:23:00  0.62063  0.62072  0.62060  0.62070
1464 2025-01-16 16:24:00  0.62070  0.62076  0.62056  0.62056
1465 2025-01-16 16:25:00  0.62056  0.62057  0.62041  0.62047
1466 2025-01-16 16:26:00  0.62048  0.62049  0.62036  0.62038
1467 2025-01-16 16:27:00  0.62040  0.62055  0.62037  0.62046
1468 2025-01-16 16:28:00  0.62046  0.62048  0.62037  0.62047
1469 2025-01-16 16:29:00  0.62047  0.62058  0.62045  0.62049
1470 2025-01-16 16:30:00  0.62051  0.62051  0.62016  0.62021
1471 2025-01-16 16:31:00  0.62018  0.62018  0.62008  0.62008
1472 2025-01-16 16:32:00  0.62007  0.62016  0.62005  0.62012
1473 2025-01-16 16:33:00  0.62012  0.62032  0.62010  0.62032
1474 2025-01-16 16:34:00  0.62033  0.62046  0.62030  0.62034
1475 2025-01-16 16:35:00  0.62034  0.62040  0.62026  0.62030
1476 2025-01-16 16:36:00  0.62029  0.62036  0.62009  0.62011
1477 2025-01-16 16:37:00  0.62010  0.62014  0.61998  0.62014
1478 2025-01-16 16:38:00  0.62013  0.62029  0.62012  0.62024
1479 2025-01-16 16:39:00  0.62024  0.62033  0.62020  0.62029
1480 2025-01-16 16:40:00  0.62029  0.62033  0.62018  0.62033
1481 2025-01-16 16:41:00  0.62033  0.62033  0.62027  0.62027
1482 2025-01-16 16:42:00  0.62030  0.62038  0.62027  0.62032
1483 2025-01-16 16:43:00  0.62032  0.62039  0.62020  0.62020
1484 2025-01-16 16:44:00  0.62020  0.62027  0.62015  0.62027
1485 2025-01-16 16:45:00  0.62028  0.62033  0.62021  0.62030
1486 2025-01-16 16:46:00  0.62032  0.62032  0.62008  0.62026
1487 2025-01-16 16:47:00  0.62024  0.62041  0.62024  0.62033
1488 2025-01-16 16:48:00  0.62033  0.62050  0.62030  0.62038
1489 2025-01-16 16:49:00  0.62038  0.62040  0.62031  0.62033
1490 2025-01-16 16:50:00  0.62032  0.62033  0.62025  0.62033

In [19]:
rates_frame.to_csv(f'./OHLC_data/{symbol}_{startdate}_{enddate}.csv', index=False)