In [24]:
# pip install --upgrade MetaTrader5

In [1]:
import numpy
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime

In [2]:
if not mt5.initialize(login=89500879, server="MetaQuotes-Demo", password="6kF-FhYd"):
    print("Initialization failed")
    print(mt5.last_error())
    quit()

print("Connected to MT5 successfully")

Connected to MT5 successfully

In [3]:
#INPUTS
# SYMBOLS = AUDSD, EURUSD,EURJPY, XAUUSD, EURGPY, USDJPY
symbol = "USDCHF"
timeframe = mt5.TIMEFRAME_M1  # 1-minute timeframe
utc_from = datetime(2025, 1, 20)
utc_to = datetime(2025, 1, 22)

In [4]:
startdate=utc_from.strftime('%Y%m%d')
enddate=utc_to.strftime('%Y%m%d')

In [5]:
# Get the OHLC data
rates = mt5.copy_rates_range(symbol, timeframe, utc_from, utc_to)

# Check if the data is downloaded successfully
if rates is None:
    print("No data available, error code =", mt5.last_error())
else:
    # Convert the data to a pandas DataFrame
    rates_frame = pd.DataFrame(rates)
    # Convert the time in seconds to a datetime format
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')

    # Display the data
    print(rates_frame)

                    time     open     high      low    close  tick_volume  \
0    2025-01-20 00:01:00  0.91310  0.91310  0.91202  0.91202            2
1    2025-01-20 00:02:00  0.91210  0.91210  0.91206  0.91206            2
2    2025-01-20 00:03:00  0.91259  0.91259  0.91206  0.91230            4
3    2025-01-20 00:05:00  0.91250  0.91250  0.91250  0.91250            1
4    2025-01-20 00:06:00  0.91321  0.91325  0.91250  0.91265            6
...                  ...      ...      ...      ...      ...          ...
1054 2025-01-20 17:37:00  0.90854  0.90868  0.90820  0.90849           67
1055 2025-01-20 17:38:00  0.90848  0.90848  0.90810  0.90820           44
1056 2025-01-20 17:39:00  0.90826  0.90851  0.90823  0.90842           58
1057 2025-01-20 17:40:00  0.90842  0.90858  0.90840  0.90852           46
1058 2025-01-20 17:41:00  0.90861  0.90890  0.90859  0.90884           20

      spread  real_volume
0         80            0
1        300            0
2        200            0
3        275            0
4         85            0
...      ...          ...
1054      13            0
1055      13            0
1056      13            0
1057      13            0
1058      12            0

[1059 rows x 8 columns]

In [6]:
rates_frame.drop(["tick_volume", "spread", "real_volume"], inplace=True, axis=1)

In [7]:
rates_frame.tail(40)

                    time     open     high      low    close
1019 2025-01-20 17:02:00  0.90749  0.90774  0.90749  0.90757
1020 2025-01-20 17:03:00  0.90756  0.90762  0.90724  0.90738
1021 2025-01-20 17:04:00  0.90739  0.90739  0.90702  0.90721
1022 2025-01-20 17:05:00  0.90724  0.90733  0.90697  0.90704
1023 2025-01-20 17:06:00  0.90702  0.90744  0.90702  0.90743
1024 2025-01-20 17:07:00  0.90744  0.90768  0.90744  0.90760
1025 2025-01-20 17:08:00  0.90760  0.90774  0.90749  0.90749
1026 2025-01-20 17:09:00  0.90748  0.90757  0.90723  0.90726
1027 2025-01-20 17:10:00  0.90725  0.90725  0.90704  0.90712
1028 2025-01-20 17:11:00  0.90714  0.90718  0.90699  0.90700
1029 2025-01-20 17:12:00  0.90693  0.90719  0.90688  0.90719
1030 2025-01-20 17:13:00  0.90723  0.90723  0.90679  0.90704
1031 2025-01-20 17:14:00  0.90704  0.90720  0.90702  0.90718
1032 2025-01-20 17:15:00  0.90717  0.90756  0.90708  0.90754
1033 2025-01-20 17:16:00  0.90756  0.90786  0.90756  0.90781
1034 2025-01-20 17:17:00  0.90781  0.90794  0.90781  0.90793
1035 2025-01-20 17:18:00  0.90790  0.90793  0.90762  0.90767
1036 2025-01-20 17:19:00  0.90766  0.90766  0.90720  0.90721
1037 2025-01-20 17:20:00  0.90716  0.90716  0.90678  0.90708
1038 2025-01-20 17:21:00  0.90709  0.90712  0.90676  0.90691
1039 2025-01-20 17:22:00  0.90690  0.90717  0.90682  0.90716
1040 2025-01-20 17:23:00  0.90713  0.90729  0.90699  0.90705
1041 2025-01-20 17:24:00  0.90704  0.90709  0.90691  0.90701
1042 2025-01-20 17:25:00  0.90697  0.90756  0.90697  0.90752
1043 2025-01-20 17:26:00  0.90754  0.90778  0.90749  0.90761
1044 2025-01-20 17:27:00  0.90757  0.90799  0.90757  0.90799
1045 2025-01-20 17:28:00  0.90800  0.90835  0.90797  0.90835
1046 2025-01-20 17:29:00  0.90832  0.90838  0.90808  0.90818
1047 2025-01-20 17:30:00  0.90818  0.90835  0.90808  0.90835
1048 2025-01-20 17:31:00  0.90838  0.90842  0.90818  0.90830
1049 2025-01-20 17:32:00  0.90829  0.90835  0.90798  0.90802
1050 2025-01-20 17:33:00  0.90803  0.90815  0.90788  0.90791
1051 2025-01-20 17:34:00  0.90793  0.90807  0.90781  0.90799
1052 2025-01-20 17:35:00  0.90799  0.90827  0.90788  0.90827
1053 2025-01-20 17:36:00  0.90826  0.90856  0.90823  0.90848
1054 2025-01-20 17:37:00  0.90854  0.90868  0.90820  0.90849
1055 2025-01-20 17:38:00  0.90848  0.90848  0.90810  0.90820
1056 2025-01-20 17:39:00  0.90826  0.90851  0.90823  0.90842
1057 2025-01-20 17:40:00  0.90842  0.90858  0.90840  0.90852
1058 2025-01-20 17:41:00  0.90861  0.90890  0.90859  0.90884

In [8]:
rates_frame.to_csv(f'./OHLC_data/{symbol}_{startdate}_{enddate}.csv', index=False)