In [1]:
pip install --upgrade MetaTrader5

Requirement already satisfied: MetaTrader5 in c:\users\aldri\appdata\local\anaconda3\lib\site-packages (5.0.4738)
Requirement already satisfied: numpy>=1.7 in c:\users\aldri\appdata\local\anaconda3\lib\site-packages (from MetaTrader5) (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime

In [3]:
# Initialize the connection
if not mt5.initialize():
    print("initialize() failed, error code =", mt5.last_error())
    quit()

In [4]:
#INPUTS
# SYMBOLS = AUDSD, EURUSD,EURJPY, XAUUSD, EURGPY, USDJPY
symbol = "EURGBP"
timeframe = mt5.TIMEFRAME_M1  # 1-minute timeframe
utc_from = datetime(2025, 1, 15)
utc_to = datetime(2025, 1, 17)

In [5]:
startdate=utc_from.strftime('%Y%m%d')
enddate=utc_to.strftime('%Y%m%d')

In [6]:
# Get the OHLC data
rates = mt5.copy_rates_range(symbol, timeframe, utc_from, utc_to)

# Check if the data is downloaded successfully
if rates is None:
    print("No data available, error code =", mt5.last_error())
else:
    # Convert the data to a pandas DataFrame
    rates_frame = pd.DataFrame(rates)
    # Convert the time in seconds to a datetime format
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')

    # Display the data
    print(rates_frame)

                    time     open     high      low    close  tick_volume  \
0    2025-01-14 16:00:00  0.84360  0.84379  0.84359  0.84376           60
1    2025-01-14 16:01:00  0.84377  0.84377  0.84354  0.84358           47
2    2025-01-14 16:02:00  0.84360  0.84370  0.84356  0.84362           46
3    2025-01-14 16:03:00  0.84363  0.84370  0.84357  0.84364           46
4    2025-01-14 16:04:00  0.84364  0.84380  0.84360  0.84380           39
...                  ...      ...      ...      ...      ...          ...
1510 2025-01-15 17:10:00  0.84145  0.84148  0.84136  0.84146           48
1511 2025-01-15 17:11:00  0.84148  0.84149  0.84129  0.84139           44
1512 2025-01-15 17:12:00  0.84139  0.84151  0.84133  0.84146           42
1513 2025-01-15 17:13:00  0.84145  0.84152  0.84138  0.84141           30
1514 2025-01-15 17:14:00  0.84141  0.84153  0.84140  0.84152           32

      spread  real_volume
0         15            0
1         15            0
2         15            0
3         15            0
4         15            0
...      ...          ...
1510      15            0
1511      15            0
1512      15            0
1513      15            0
1514      15            0

[1515 rows x 8 columns]

In [7]:
rates_frame.drop(["tick_volume", "spread", "real_volume"], inplace=True, axis=1)

In [8]:
rates_frame.tail(40)

                    time     open     high      low    close
1475 2025-01-15 16:35:00  0.84059  0.84060  0.84047  0.84050
1476 2025-01-15 16:36:00  0.84051  0.84070  0.84049  0.84067
1477 2025-01-15 16:37:00  0.84070  0.84082  0.84065  0.84074
1478 2025-01-15 16:38:00  0.84076  0.84078  0.84051  0.84054
1479 2025-01-15 16:39:00  0.84054  0.84057  0.84048  0.84054
1480 2025-01-15 16:40:00  0.84053  0.84061  0.84046  0.84056
1481 2025-01-15 16:41:00  0.84056  0.84069  0.84048  0.84068
1482 2025-01-15 16:42:00  0.84069  0.84078  0.84064  0.84074
1483 2025-01-15 16:43:00  0.84070  0.84073  0.84057  0.84058
1484 2025-01-15 16:44:00  0.84058  0.84070  0.84058  0.84069
1485 2025-01-15 16:45:00  0.84068  0.84076  0.84056  0.84072
1486 2025-01-15 16:46:00  0.84073  0.84089  0.84067  0.84086
1487 2025-01-15 16:47:00  0.84086  0.84088  0.84078  0.84084
1488 2025-01-15 16:48:00  0.84084  0.84085  0.84073  0.84084
1489 2025-01-15 16:49:00  0.84083  0.84090  0.84071  0.84087
1490 2025-01-15 16:50:00  0.84087  0.84107  0.84086  0.84107
1491 2025-01-15 16:51:00  0.84106  0.84110  0.84096  0.84107
1492 2025-01-15 16:52:00  0.84107  0.84123  0.84100  0.84122
1493 2025-01-15 16:53:00  0.84122  0.84131  0.84119  0.84122
1494 2025-01-15 16:54:00  0.84124  0.84149  0.84121  0.84140
1495 2025-01-15 16:55:00  0.84141  0.84174  0.84138  0.84146
1496 2025-01-15 16:56:00  0.84144  0.84159  0.84142  0.84159
1497 2025-01-15 16:57:00  0.84158  0.84176  0.84151  0.84171
1498 2025-01-15 16:58:00  0.84170  0.84194  0.84161  0.84194
1499 2025-01-15 16:59:00  0.84197  0.84200  0.84175  0.84175
1500 2025-01-15 17:00:00  0.84176  0.84180  0.84150  0.84161
1501 2025-01-15 17:01:00  0.84160  0.84166  0.84132  0.84141
1502 2025-01-15 17:02:00  0.84141  0.84152  0.84130  0.84131
1503 2025-01-15 17:03:00  0.84130  0.84134  0.84120  0.84120
1504 2025-01-15 17:04:00  0.84120  0.84179  0.84120  0.84177
1505 2025-01-15 17:05:00  0.84176  0.84179  0.84155  0.84157
1506 2025-01-15 17:06:00  0.84155  0.84161  0.84150  0.84153
1507 2025-01-15 17:07:00  0.84151  0.84160  0.84145  0.84147
1508 2025-01-15 17:08:00  0.84144  0.84154  0.84137  0.84140
1509 2025-01-15 17:09:00  0.84139  0.84150  0.84136  0.84145
1510 2025-01-15 17:10:00  0.84145  0.84148  0.84136  0.84146
1511 2025-01-15 17:11:00  0.84148  0.84149  0.84129  0.84139
1512 2025-01-15 17:12:00  0.84139  0.84151  0.84133  0.84146
1513 2025-01-15 17:13:00  0.84145  0.84152  0.84138  0.84141
1514 2025-01-15 17:14:00  0.84141  0.84153  0.84140  0.84152

In [9]:
rates_frame.to_csv(f'./OHLC_data/{symbol}_{startdate}_{enddate}.csv', index=False)