In [1]:
import numpy
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime

In [2]:
if not mt5.initialize(login=89500879, server="MetaQuotes-Demo", password="6kF-FhYd"):
    print("Initialization failed")
    print(mt5.last_error())
    quit()

print("Connected to MT5 successfully")

Connected to MT5 successfully

In [3]:
#INPUTS
# SYMBOLS = AUDSD, EURUSD,EURJPY, XAUUSD, EURGPY, USDJPY
symbol = "AUDUSD"
timeframe = mt5.TIMEFRAME_M1  # 1-minute timeframe
utc_from = datetime(2025, 1, 27)
utc_to = datetime(2025, 1, 29)

In [4]:
startdate=utc_from.strftime('%Y%m%d')
enddate=utc_to.strftime('%Y%m%d')

In [5]:
# Get the OHLC data
rates = mt5.copy_rates_range(symbol, timeframe, utc_from, utc_to)

# Check if the data is downloaded successfully
if rates is None:
    print("No data available, error code =", mt5.last_error())
else:
    # Convert the data to a pandas DataFrame
    rates_frame = pd.DataFrame(rates)
    # Convert the time in seconds to a datetime format
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')

    # Display the data
    print(rates_frame)

                   time     open     high      low    close  tick_volume  \
0   2025-01-27 00:00:00  0.62931  0.62931  0.62931  0.62931            1
1   2025-01-27 00:01:00  0.62931  0.63089  0.62931  0.63004            7
2   2025-01-27 00:02:00  0.63003  0.63025  0.63001  0.63025           12
3   2025-01-27 00:03:00  0.63026  0.63032  0.63026  0.63032            5
4   2025-01-27 00:04:00  0.63027  0.63027  0.63004  0.63004            6
..                  ...      ...      ...      ...      ...          ...
995 2025-01-27 16:35:00  0.62900  0.62909  0.62888  0.62909           60
996 2025-01-27 16:36:00  0.62909  0.62910  0.62887  0.62890           53
997 2025-01-27 16:37:00  0.62890  0.62890  0.62871  0.62881           57
998 2025-01-27 16:38:00  0.62881  0.62893  0.62881  0.62888           54
999 2025-01-27 16:39:00  0.62890  0.62890  0.62874  0.62881           38

     spread  real_volume
0       171            0
1        84            0
2        59            0
3        53            0
4        54            0
..      ...          ...
995       8            0
996       9            0
997       8            0
998      10            0
999      10            0

[1000 rows x 8 columns]

In [6]:
rates_frame.drop(["tick_volume", "spread", "real_volume"], inplace=True, axis=1)

In [7]:
rates_frame.tail(40)

                   time     open     high      low    close
960 2025-01-27 16:00:00  0.62921  0.62936  0.62908  0.62908
961 2025-01-27 16:01:00  0.62907  0.62924  0.62906  0.62922
962 2025-01-27 16:02:00  0.62921  0.62932  0.62916  0.62932
963 2025-01-27 16:03:00  0.62931  0.62933  0.62916  0.62917
964 2025-01-27 16:04:00  0.62917  0.62917  0.62891  0.62894
965 2025-01-27 16:05:00  0.62897  0.62910  0.62896  0.62905
966 2025-01-27 16:06:00  0.62907  0.62919  0.62902  0.62918
967 2025-01-27 16:07:00  0.62918  0.62929  0.62910  0.62925
968 2025-01-27 16:08:00  0.62924  0.62933  0.62921  0.62923
969 2025-01-27 16:09:00  0.62923  0.62926  0.62915  0.62922
970 2025-01-27 16:10:00  0.62924  0.62938  0.62918  0.62931
971 2025-01-27 16:11:00  0.62930  0.62934  0.62926  0.62931
972 2025-01-27 16:12:00  0.62934  0.62936  0.62922  0.62934
973 2025-01-27 16:13:00  0.62933  0.62933  0.62917  0.62920
974 2025-01-27 16:14:00  0.62921  0.62929  0.62889  0.62891
975 2025-01-27 16:15:00  0.62892  0.62892  0.62879  0.62883
976 2025-01-27 16:16:00  0.62884  0.62895  0.62884  0.62886
977 2025-01-27 16:17:00  0.62886  0.62900  0.62884  0.62892
978 2025-01-27 16:18:00  0.62892  0.62905  0.62892  0.62903
979 2025-01-27 16:19:00  0.62901  0.62915  0.62901  0.62910
980 2025-01-27 16:20:00  0.62910  0.62919  0.62906  0.62914
981 2025-01-27 16:21:00  0.62914  0.62915  0.62899  0.62899
982 2025-01-27 16:22:00  0.62897  0.62915  0.62897  0.62913
983 2025-01-27 16:23:00  0.62915  0.62919  0.62901  0.62901
984 2025-01-27 16:24:00  0.62900  0.62900  0.62886  0.62890
985 2025-01-27 16:25:00  0.62892  0.62895  0.62881  0.62885
986 2025-01-27 16:26:00  0.62885  0.62887  0.62869  0.62879
987 2025-01-27 16:27:00  0.62879  0.62881  0.62859  0.62861
988 2025-01-27 16:28:00  0.62862  0.62876  0.62860  0.62870
989 2025-01-27 16:29:00  0.62867  0.62877  0.62867  0.62871
990 2025-01-27 16:30:00  0.62868  0.62884  0.62860  0.62866
991 2025-01-27 16:31:00  0.62869  0.62883  0.62855  0.62876
992 2025-01-27 16:32:00  0.62877  0.62892  0.62870  0.62871
993 2025-01-27 16:33:00  0.62870  0.62900  0.62869  0.62899
994 2025-01-27 16:34:00  0.62899  0.62903  0.62895  0.62900
995 2025-01-27 16:35:00  0.62900  0.62909  0.62888  0.62909
996 2025-01-27 16:36:00  0.62909  0.62910  0.62887  0.62890
997 2025-01-27 16:37:00  0.62890  0.62890  0.62871  0.62881
998 2025-01-27 16:38:00  0.62881  0.62893  0.62881  0.62888
999 2025-01-27 16:39:00  0.62890  0.62890  0.62874  0.62881

In [8]:
rates_frame.to_csv(f'./OHLC_data/{symbol}_{startdate}_{enddate}.csv', index=False)